% test gradient torque for z gradients only
function test_torque_z()
  d = 0.00012

  % standard matrices
  ee = zeros(3,3,3);
  ee(1,2,3) = 1;
  ee(2,3,1) = 1;
  ee(3,1,2) = 1;
  ee(3,2,1) = -1;
  ee(2,1,3) = -1;
  ee(1,3,2) = -1;

  dd=[1 0 0; 0 1 0; 0 0 1];

  % 3x3 coordinate grid
  for i=1:3; for j=1:3, for k=1:3
    xx(i,j,k) = (i-2)*d;
    yy(i,j,k) = (j-2)*d;
    zz(i,j,k) = (k-2)*d;
  end; end; end

  ma = rand*pi + zz*(rand-0.5) + zz.*zz*2*(rand-0.5);
  mb = rand*pi + zz*(rand-0.5) + zz.*zz*2*(rand-0.5);
  mt = rand*pi + zz*(rand-0.5) + zz.*zz*2*(rand-0.5);

  % n vector and R matrix
  mn = zeros(3,3,3,3);
  mR = zeros(3,3,3,3,3);
  for i=1:3; for j=1:3, for k=1:3
    mn(i,j,k,:)=[sin(mb(i,j,k))*cos(ma(i,j,k)) sin(mb(i,j,k))*sin(ma(i,j,k)) cos(mb(i,j,k))];
    mR(i,j,k,:,:) = rmatr_nt(mn(i,j,k,:),mt(i,j,k));
  end; end; end

  % gradients: ggR(k,m,a,j) == nabla_k nabla_m R_aj
  for a=1:3; for j=1:3
    [vR(a,j), gR(:,a,j), ggR(:,:,a,j)] = vmatr2grad(squeeze(mR(:,:,:,a,j)), d);
  end; end
  for a=1:3;
    [vn(a), gn(:,a), ggn(:,:,a)] = vmatr2grad(squeeze(mn(:,:,:,a)), d);
  end
  [vt, gt, ggt] = vmatr2grad(mt, d);
  ct = cos(vt); st=sin(vt);


  %%%%%%%%%%%%%%%%%%%
  % torque-1
  T1a=zeros(3,1);
  T1b=zeros(3,1);
  for a=1:3; for b=1:3; for c=1:3; for j=1:3; for k=1:3;
    T1a(a) = T1a(a) + ee(a,b,c)*vR(c,j)*ggR(k,k,b,j);
    T1b(a) = T1b(a) + ee(a,b,c)*vR(c,j)*ggR(k,j,b,k);
  end; end; end; end; end;

  % torque-2
  T2a=zeros(3,1);
  T2b=zeros(3,1);
  for a=1:3; for b=1:3; for c=1:3; for j=1:3; for k=1:3; for m=1:3;
    T2a(b) = T2a(b) + ee(b,a,c)*vR(c,j)* (
       + dd(m,1) * ct*(vn(a)*vn(j)-dd(a,j))*gt(k)*gt(k) ...
       + dd(m,1) * st*(vn(a)*gn(k,j)+vn(j)*gn(k,a))*gt(k) ...
       + dd(m,1) * st*(vn(a)*vn(j)-dd(a,j))*ggt(k,k) ...
       + dd(m,1) * (1-ct)*(gn(k,j)*gn(k,a) + gn(k,a)*gn(k,j)) ...
       + dd(m,1) * (1-ct)*(vn(j)*ggn(k,k,a) + vn(a)*ggn(k,k,j)) ...
       + dd(m,1) * st*(vn(j)*gn(k,a) + vn(a)*gn(k,j))*gt(k) ...
       + st * ee(a,j,m) * vn(m) * gt(k)*gt(k) ...
       - ct * ee(a,j,m) * gn(k,m) * gt(k) ...
       - ct * ee(a,j,m) * vn(m) * ggt(k,k) ...
       - ct * ee(a,j,m) * gn(k,m) * gt(k) ...
       - st * ee(a,j,m) * ggn(k,k,m) ...
    );
    T2b(b) = T2b(b) + ee(b,a,c)*vR(c,j)* (
       + dd(m,1) * ct*(vn(a)*vn(k)-dd(a,k))*gt(j)*gt(k) ...
       + dd(m,1) * st*(vn(a)*gn(k,k)+vn(k)*gn(k,a))*gt(j) ...
       + dd(m,1) * st*(vn(a)*vn(k)-dd(a,k))*ggt(j,k) ...
       + dd(m,1) * (1-ct)*(gn(k,k)*gn(j,a) + gn(k,a)*gn(j,k)) ...
       + dd(m,1) * (1-ct)*(vn(k)*ggn(j,k,a) + vn(a)*ggn(j,k,k)) ...
       + dd(m,1) * st*(vn(k)*gn(j,a) + vn(a)*gn(j,k))*gt(k) ...
       + st * ee(a,k,m) * vn(m) * gt(k)*gt(j) ...
       - ct * ee(a,k,m) * gn(k,m) * gt(j) ...
       - ct * ee(a,k,m) * vn(m) * ggt(k,j) ...
       - ct * ee(a,k,m) * gn(j,m) * gt(k) ...
       - st * ee(a,k,m) * ggn(k,j,m) ...
    );
  end; end; end; end; end; end;

  r1 = sum((T1a-T2a).^2);
  r2 = sum((T1b-T2b).^2);
  fprintf('test torque 1. A: %e B: %e\n', r1,r2);

  % torque-3
  T2a=zeros(3,1);
  T2b=zeros(3,1);
  for a=1:3; for b=1:3; for j=1:3; for k=1:3; for m=1:3;
    T2a(b) = T2a(b) ...
... % gn gt
       - 2*dd(a,1)*dd(m,1)*dd(j,1)*dd(k,3) *(1+ct)  * gn(3,b)*gt(3) ...
       + 2*dd(a,1)*dd(k,3)                 *st   *ee(b,j,m) *vn(m)*gn(3,j)*gt(3) ...
... % ggn
       - dd(a,1)*dd(m,1)*dd(j,1)*dd(k,3) *2*st        *ggn(3,3,b) ...
       - dd(a,1)*dd(k,3)                 *2*(1-ct)    *ee(m,j,b) * vn(m)*ggn(3,3,j) ...
       + dd(a,1)*dd(m,1)*dd(k,3)         *2*st*(1-ct) *vn(b)*vn(j)*ggn(3,3,j) ...
... % ggt
       - dd(a,1)*dd(m,1)*dd(j,1)*dd(k,3) *2*vn(b)     *ggt(3,3) ...
... % gn gn
       + dd(a,1)*dd(m,1)*dd(k,3)         *2*(1-ct)*st *vn(b)*gn(3,j)^2;



    T2b(b) = T2b(b) ...
...% gt gt
       - dd(a,1)*dd(m,1)*dd(k,1)*dd(j,3)*dd(c,3) *st  *dd(b,c)*vn(3) * gt(3)^2 ...
       + dd(a,1)*dd(m,1)*dd(k,3)*dd(j,3)         *st  *vn(b)*vn(3)*vn(3) *gt(3)^2 ...
       + dd(m,1)*dd(k,3)*dd(a,3)                 *ct  *ee(b,j,3) *vn(j)*vn(3) *gt(3)^2 ...
...% gn gn
       + dd(j,1)*dd(m,1)*dd(k,3)*dd(a,3) *vn(b) *  2*st*(1-ct)*gn(3,3)^2 ...
       + dd(m,1)*dd(k,3)*dd(j,3)  *2*ct*(1-ct) *ee(b,a,3)*gn(3,3)*gn(3,a) ...
       + dd(k,3)*dd(j,3) * 2*(1-ct)^2  *ee(b,a,m)*vn(m)*vn(3) *gn(3,3)*gn(3,a) ...
...% gn gt
       - dd(a,1)*dd(m,1)*dd(k,1)*dd(j,3)          *2*ct^2  * gn(3,b)*gt(3) ...
       + dd(a,1)*dd(m,1)*dd(k,1)*dd(j,3)*dd(c,3)  *2*(ct^2-st^2) * dd(b,c) * gn(3,3)*gt(3) ...
       - dd(a,1)*dd(m,1)*dd(j,3)*dd(k,3)          *(1-ct)*ct* vn(3)^2  *2*gn(3,b) * gt(3) ...
       + dd(a,1)*dd(k,1)*dd(j,3)*dd(m,3)          *4*st*st* vn(b) * vn(3)*gn(3,3)*gt(3) ...
       + dd(m,1)*dd(j,3)*dd(k,3)  *2*ct*st  *ee(b,a,3) *vn(a) * gn(3,3) * gt(3) ...
       + dd(m,1)*dd(j,3)*dd(k,3)  *2*ct*st  *ee(b,a,3) *vn(3) * gn(3,a) * gt(3) ...
       + dd(m,1)*dd(c,3)*dd(k,3)  *2*ct*st  *ee(a,3,j) *vn(a) * gn(3,j) * gt(3)  * dd(b,c) ...
       + dd(j,3)*dd(k,3)          *2*(1-ct)*st *ee(b,a,m)*vn(m)*vn(3)^2*gn(3,a)*gt(3) ...
...% ggt
       + dd(a,1)*dd(m,1)*dd(k,1)*dd(j,3)*dd(c,3) *ct^2 * vn(j) * ggt(3,3) * dd(b,c)...
       - dd(a,1)*dd(m,1)*dd(k,1)*dd(j,3)         *vn(b) * ggt(3,3) ...
       + dd(a,1)*dd(k,1)*dd(m,1)*dd(j,3)*dd(c,3) *(1-ct)*ct* vn(3) * ggt(3,3) * dd(b,c) ...
       + dd(a,1)*dd(m,1)*dd(j,3)*dd(k,3) *(1-ct)    *vn(b)*vn(3)^2 * ggt(3,3) ...
       + dd(k,1)*dd(m,3)*dd(j,3)  *st *ee(b,a,3)*vn(a)*vn(3)*ggt(3,3) ...
...% ggn
       - dd(a,1)*dd(m,1)*dd(k,1)*dd(j,3) *ct * st     * ggn(3,3,b) ...
       + dd(a,1)*dd(m,1)*dd(k,1)*dd(c,3)*dd(j,3) *(2*ct-1)*st* ggn(3,3,3)* dd(b,c) ...
       - dd(a,1)*dd(m,1)*dd(j,3)*dd(k,3) *(1-ct)*st *vn(3)*vn(3) * ggn(3,3,b) ...
       + dd(j,1)*dd(m,1)*dd(a,3)*dd(k,3) *2*(1-ct)*st *vn(b)*vn(3) * ggn(3,3,3) ...
       + dd(m,1)*dd(j,3)*dd(k,3) *ct*(1-ct) *ee(b,a,3) *vn(3) * ggn(3,3,a) ...
       + dd(m,1)*dd(j,3)*dd(k,3) *ct*(1-ct) *ee(b,a,3) *vn(a) * ggn(3,3,3) ...
       + dd(m,1)*dd(k,3)*dd(c,3) *st*st     *ee(a,3,j) *vn(a) * ggn(3,3,j) * dd(b,c) ...
       + dd(k,1)*dd(j,3)    * (1-ct)*ee(b,a,m)*vn(m)*vn(3) * (1-ct)*vn(3)*ggn(3,3,a);

  end; end; end; end; end;

  r1 = sum((T1a-T2a).^2);
  r2 = sum((T1b-T2b).^2);
  fprintf('test torque 2. A: %e B: %e\n', r1,r2);


end
